### ISSUE TITLE
isSpammer() just seems to hang

### ISSUE THREAD

**Issue by codecowboy** [deltreey/stopforumspam#4]
This code just seems to max out the CPU and not actually do anything. A result is not received. Would be grateful for any insight - I'e tried remote debugging but cant seem to see the redponde from the API.
```
var checkSpam = function(entry) {
console.log('checking spam '+entry.poster);
    stopforumspam.isSpammer({ email: entry.email, username: entry.poster })
        .then(function (result) {


            write_spam_to_file(result.stringify());
            console.log('there was a result '+result.stringify());

        });
}
```

**Comment by deltreey** [comment]
thanks for the bug report, will try and reproduce

**Comment by deltreey** [comment]
I added a test that mimics this exactly and it works fine.  I even tested passing in null/undefined parameters.

https://github.com/deltreey/stopforumspam/commit/f8b1e1bf487f4265cbf75847ec0dd1b25ce28934#diff-c1129c8b045390789fa8ff62f2c6b4a9R201

Added lots of tests thanks to this issue, but I'm going to have to mark this as cannot reproduce.  Please reopen if you can gather more information about the issue you're having.

**Comment by codecowboy** [comment]
@deltreey I realise it has been a while since I opened this issue. I am revisiting the issue and am still getting this behaviour. To be honest, I think this is die to my continued misunderstanding of async i/o but I would be grateful for any assistance.
```

    connection.query(firstPostQuery,{ x: whiteListString }, function( err, rows ) {

        if (err) throw err;

        rows.forEach(function(item){

            results.push(item);
        });

        console.log(results.length);


        for(var i = 0; i < results.length; i ++ ) {
            sfs.isSpammer({
                ip: results[i].ip,
                email: results[i].email,
                username: results[i].poster
            }).then(function (result) {

                if (result.username.appears === 1) {

                    console.log(result.toJSON());
                    fs.appendFile(__dirname + '/stopforumspam.txt', item.poster + '\n',
                        function (err) {
                            if (err) throw err;

                        })(result);

                } else {

                    fs.appendFile(__dirname + '/stopforumspam.txt',
                        'nope\n',
                        function (err) {
                            if (err) throw err;
                        });
                }

            }); //end then
        } //end for

    });
```

**Comment by deltreey** [comment]
I don't think the `appears` property is a flag.  I think it is numeric, as in, the number of times the data appears.  You should not check for it to be `=== 1`, but simply `> 0`.  I will take a closer look at your example.  What database are you running your connection to?  I have a strong sense it's the database part that's been your trouble. all along.

**Comment by codecowboy** [comment]
thanks. It's MySQL - I've tried both node-mysql and mysql2. I think that it may just be that the array is 3000+ items and the combination of Node and the SFS service just can't cope with that many requests all at once. I haven't yet found an effective way to mitigate that.

**Comment by deltreey** [comment]
Here's an example test I slapped together.  There's a lot to understand here, so I'll walk you through it.  Rather than getting super promisey, I'm just using callbacks to keep it simple, if ugly.

The test includes a `done` parameter, which means the test will wait for that callback to be called to consider the result complete.  If the `done` callback receives anything as it's first parameter, it considers that an error and fails the test.

I increased the test timeout to 10 seconds.  Mocha defaults to 2 seconds, which isn't enough for multiple http requests to return (in my case 12).

I'm using [node-mysql](https://github.com/redblaze/node-mysql#db-connect) since you said you were familiar with it. In order to track my iteration over each record, I am using [asyncjs](https://github.com/caolan/async#each).  It's just like a foreach loop, but you call a callback after each time through the loop to declare yourself finished.  It runs in parallel by default, but you can [limit the number of parallel iterations](https://github.com/caolan/async#documentation) and [force all iterations to be in series](https://github.com/caolan/async#documentation) if you prefer pretty easily.

When you connect to the database, you get 2 parameters to your callback.  The first is the connection, and the second is another callback.  I'm guessing the purpose of the callback is to notify the connection that you're done with it and it can close, so I call it `closeConnection`.

Then, when you query the database, your second parameter is a callback to deal with the results of that query.  In traditional node style, the first parameter of the callback is any errors which you should deal with before moving on[1].  The second is the results of the query as some fancy javascript objects.  It was pretty easy to map this data to some sfsUser objects, but I kept with the pattern you used here also.  `then` is the callback part of the promise, so in the then we get our data from stopforumspam back and can do stuff.  Then we want to make sure and callback the `eachCallback` so the loop knows it can continue.  I like to put return on these lines so I know this is terminating the function.  That's a good practice as you look toward moving toward cleaner async code in general.

The `async.each` callback for each record is in traditional node style as well, just like the done callback and the query callback.  So I don't pass a parameter if successful.  Promises pass the error if catch is called, so I don't need to do anything special, just pass in the `eachCallback` function so that the catch block can call it if there's a problem.

The first parameter for `async.each` is the array, the second is the function to call on each record of the array.  The third is the callback to call when everything is done with your array.  You see that here I pass in the `closeConnection` callback.  While we might have been able to close the connection sooner, I don't want to chance that this mysql library is trying to do some weird optimization and would lose my records if I did that, so I call it once we're done working with everything.

Calling the `closeConnection` callback naturally closes our connection callback, thus triggering it's callback to fire.  In this case, I can simply pass in the `done` callback from our test to let it know that everything is wrapped up and we are ready to see the results.

Let me know if you have any trouble with this demo.

```javascript
it('works with databases', function (done) {
	this.timeout(10000);	// increase timeout since http is laggy
	var mysql = require('node-mysql');
	var async = require('async');

	var db = new mysql.DB({
		host: 'localhost',
		user: 'root',
		password: '***',
		database: 'testdrive_db'
	});
	db.connect(function (connection, closeConnection) {
		connection.query('SELECT * FROM employees;', function (error, results) {
			// limit your concurrent http requests to reduce problems
			async.each(results, function (record, eachCallback) {
				// however you map the data
				var username = record.firstname;
				var email = record.firstname + '@' + record.lastname + '.com';
				var ip = '127.0.0.1';
				stopforumspam.isSpammer({ username: username, email: email, ip: ip })
				.then(function (result) {
					// do stuff with result
					console.log(result.success);
					return eachCallback();
				})
				.catch(eachCallback);
			}, closeConnection);
		});
	}, done);
});
```

[1] - You have not dealt with errors in any of your examples thusfar, so it's hard to help you because I can't know what's wrong.
